# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rackspace Design System
email: design-system@rackspace.com
description: > # this means to ignore newlines until "baseurl:"
  Designed out of the best parts of Encore 2.0, Canon, and other Rackspace interfaces, Helix is an initial step toward a 
  shared set of UX/UI components that designers and developers can use to deliver high quality, cohesive experiences for 
  customers and Rackers alike.
baseurl: "http://design.rax.io/design-system" # the subpath of your site, e.g. /blog
url: "http://design.rax.io/design-system" # the base hostname & protocol for your site
twitter_username: rackspace
github_username:  rackerlabs
permalink: /:categories/:slug
navigation: ['Style', 'Layout', 'Components', 'Templates']
exclude: ['Gemfile', 'Gemfile.lock','README.md','vendor']


# PATHING FOR WEBSITE AND DESIGN-SYSTEM
websiteAssets: '/assets/website/'


# Build settings
markdown: redcarpet
highlighter: rouge
gems:
- jekyll-compass
