# Staging site settings
title: Staging - Rackspace Design System
baseurl: "http://staging.design.rax.io/design-system"
url: "http://staging.design.rax.io/design-system"
navigation: ['Style', 'Layout', 'Components', 'Templates']
