#!/usr/bin/env bash

set -e

log () {
  echo -e "\e[1m==> $@\e[0m"
}

error () {
  echo -e "\e[31;1m$@\e[0m"
}

success () {
  echo -e "\e[32;1m$@\e[0m"
}

warn () {
  echo -e "\e[33;1m$@\e[0m"
}

info () {
  echo -e "\e[36;1m$@\e[0m"
}

show_welcome_message () {
  echo ""
  info "Welcome to the Rackspace Design System!"
  echo ""

  cat <<-MESSAGE
Before you get started contributing to the Design System, let's make sure that your
development environment has all the necessary dependencies. This script will:

  - Check for RVM or rbenv
  - Check for Ruby 2.x.x
  - Install Bundler
  - Install Ruby dependencies

Press ENTER to continue.
MESSAGE

  read
}

check_version_manager () {
  log "Checking for Ruby version manager..."

  if [[ -z "$(command -v rvm)" && -z "$(command -v rbenv)" && -z "$(command -v chruby)" ]]; then
    warn "\nYou don't have a Ruby version manager installed. Proceed with caution.\n"
  fi
}

check_ruby_version () {
  log "Checking Ruby version..."

  version="$(ruby --version)"

  if ! [[ "$version" =~ "ruby 2" || "$version" =~ "ruby 1.9" ]]; then
    error "\nCanon required Ruby 2.x.x. Please update Ruby and try again.\n"
    exit 1
  fi
}

install_bundler () {
  log "Installing Bundler..."
  gem install bundler
}

install_gems () {
  log "Installing Ruby gems..."
  bundle install
}


if [[ $CI != true ]]; then
  show_welcome_message
fi

check_version_manager
check_ruby_version
check_node_version

install_bundler
install_gems


success "\nRackspace Design System setup completed successfully!\n"
